apiVersion: v1
kind: Service
metadata:
  name: apollo
  labels:
    app: apollo
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: apollo
  type: LoadBalancer